---
- name: Apache server installation on client1
  hosts: client1
  remote_user: root
  tasks: 
  - name: apache installation on client1
    yum: name=httpd state=present 
  - name: creating in webpage in client
    copy: dest=/var/www/html/index.html content="This is test page"
  - name: starting the apache service
    service: name=httpd state=restarted enabled=yes
