---

- name: list /tmp and append that list to a file
  hosts: TEST
  gather_facts: no
  become: True


  tasks:

  - name: check whether file /var/tmp/outfile exists
    shell: if ls -l /var/tmp/outfile;then echo "fileis";else echo "nofile";fi 
    register: file_exists

  - name: create if /var/tmp/outfile doesn't exist.
    file: 
     path: /var/tmp/outfile
     state: touch
    register: fileexists_out
    when: file_exists.stdout == "nofile"

  - name: List files under /tmp
    shell: 'ls /tmp'
    register: lstmp_output

  - name: append the above list to a file in /var/tmp/outfile
    lineinfile:
      path: '/var/tmp/outfile'
      state: present 
      line: '{{ item }}'
    with_items: 
      - '{{ lstmp_output.stdout }}'
    when: lstmp_output|changed
    
