---

- name: generating standard motd
  hosts: TEST
  become: True

  tasks:
  - name: copy standard motd to all hosts
    template:
      src: /etc/ansible/Ansible-project/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
 
